---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    name: hello
spec:
  replicas: 1
  template:
    metadata:
      name: hello
      labels:
        name: hello
    spec:
      containers:
        - name: hello
          image: bazel:hello_img
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    name: hello
spec:
  type: NodePort
  ports:
    - port: 50051
      nodePort: 30001
  selector:
    name: hello
